
namespace NERP.Configuration
{
    using Serenity;
    using Serenity.ComponentModel;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    [Imported, Serializable, PreserveMemberCase]
    public partial class ItemTaxRow
    {
        [InlineConstant] public const string IdProperty = "Id";
        [InlineConstant] public const string NameProperty = "Code";
        [InlineConstant] public const string IsActiveProperty = "IsActive";
        [InlineConstant] public const string LocalTextPrefix = "Configuration.ItemTax";

        public Int32? Id { get; set; }
        public String Code { get; set; }
        public String Name { get; set; }
        public String Description { get; set; }
        public Int32? ItemId { get; set; }
        public Int32? TaxId { get; set; }
        public Decimal? Rate { get; set; }
        public String Note { get; set; }
        public Int32? ProjectId { get; set; }
        public Int32? OrganogramId { get; set; }
        public Int32? ScopeId { get; set; }
        public Int32? CompanyId { get; set; }
        public Int32? StatusId { get; set; }
        public String ActiveOn { get; set; }
        public String InactiveOn { get; set; }
        public Int16? IsActive { get; set; }
        public Int32? DbId { get; set; }
        public Int32? CreatedBy { get; set; }
        public String CreatedOn { get; set; }
        //public String CreatedPc { get; set; }
        public Int32? UpdatedBy { get; set; }
        public String UpdatedOn { get; set; }
        //public String UpdatedPc { get; set; }
        public Int32? DeletedBy { get; set; }
        public String DeletedOn { get; set; }
        //public String DeletedPc { get; set; }
        public Int16? IsDelete { get; set; }
        public String ItemCode { get; set; }
        public String ItemName { get; set; }
        public String ItemDescription { get; set; }
        public Int32? ItemItemGroupId { get; set; }
        public Int32? ItemUomId { get; set; }
        public Int32? ItemImageId { get; set; }
        public Int32? ItemSpecificationId { get; set; }
        public Int32? ItemColorId { get; set; }
        public Int32? ItemSizeId { get; set; }
        public Int32? ItemModelId { get; set; }
        public Int32? ItemStyleId { get; set; }
        public Int32? ItemBrandId { get; set; }
        public Int32? ItemCountryId { get; set; }
        public Int32? ItemSeasonId { get; set; }
        public Int32? ItemPurposeId { get; set; }
        public Int32? ItemSupplierId { get; set; }
        public Int32? ItemConditionId { get; set; }
        public Int32? ItemQualityId { get; set; }
        public Int32? ItemYear { get; set; }
        public String ItemExpireDate { get; set; }
        public Int32? ItemLifeTime { get; set; }
        public String ItemBarcode { get; set; }
        public Decimal? ItemUnitWeight { get; set; }
        public Int32? ItemWeightUomId { get; set; }
        public Decimal? ItemReorderLevel { get; set; }
        public Decimal? ItemCostPrice { get; set; }
        public Decimal? ItemSellingPrice { get; set; }
        public Decimal? ItemPromoPrice { get; set; }
        public String ItemPromoStartDate { get; set; }
        public String ItemPromoEndDate { get; set; }
        public Decimal? ItemCommissionAmt { get; set; }
        public Int16? ItemIsCommissionPercent { get; set; }
        public Int16? ItemIsTaxInclude { get; set; }
        public Int16? ItemIsOverrideTax { get; set; }
        public String ItemTax1 { get; set; }
        public String ItemTax2 { get; set; }
        public String ItemTax3 { get; set; }
        public String ItemTax4 { get; set; }
        public String ItemTax5 { get; set; }
        public Decimal? ItemTax1Rate { get; set; }
        public Decimal? ItemTax2Rate { get; set; }
        public Decimal? ItemTax3Rate { get; set; }
        public Decimal? ItemTax4Rate { get; set; }
        public Decimal? ItemTax5Rate { get; set; }
        public Decimal? ItemDefaultQty { get; set; }
        public String ItemDefaultLocationAtStore { get; set; }
        public String ItemNote { get; set; }
        public Int32? ItemProjectId { get; set; }
        public Int32? ItemOrganogramId { get; set; }
        public Int32? ItemScopeId { get; set; }
        public Int32? ItemCompanyId { get; set; }
        public Int32? ItemStatusId { get; set; }
        public String ItemActiveOn { get; set; }
        public String ItemInactiveOn { get; set; }
        public Int16? ItemIsActive { get; set; }
        public Int32? ItemDbId { get; set; }
        public Int32? ItemCreatedBy { get; set; }
        public String ItemCreatedOn { get; set; }
        public String ItemCreatedPc { get; set; }
        public Int32? ItemUpdatedBy { get; set; }
        public String ItemUpdatedOn { get; set; }
        public String ItemUpdatedPc { get; set; }
        public Int32? ItemDeletedBy { get; set; }
        public String ItemDeletedOn { get; set; }
        public String ItemDeletedPc { get; set; }
        public Int16? ItemIsDelete { get; set; }
        public String TaxCode { get; set; }
        public String TaxName { get; set; }
        public String TaxDescription { get; set; }
        public Decimal? TaxRate { get; set; }
        public Int16? TaxIsDefault { get; set; }
        public String TaxNote { get; set; }
        public Int32? TaxProjectId { get; set; }
        public Int32? TaxOrganogramId { get; set; }
        public Int32? TaxScopeId { get; set; }
        public Int32? TaxCompanyId { get; set; }
        public Int32? TaxStatusId { get; set; }
        public String TaxActiveOn { get; set; }
        public String TaxInactiveOn { get; set; }
        public Int16? TaxIsActive { get; set; }
        public Int32? TaxDbId { get; set; }
        public Int32? TaxCreatedBy { get; set; }
        public String TaxCreatedOn { get; set; }
        public String TaxCreatedPc { get; set; }
        public Int32? TaxUpdatedBy { get; set; }
        public String TaxUpdatedOn { get; set; }
        public String TaxUpdatedPc { get; set; }
        public Int32? TaxDeletedBy { get; set; }
        public String TaxDeletedOn { get; set; }
        public String TaxDeletedPc { get; set; }
        public Int16? TaxIsDelete { get; set; }

        [Imported, PreserveMemberCase]
        public static class Fields
        {
            [InlineConstant] public const string Id = "Id";
            [InlineConstant] public const string Code = "Code";
            [InlineConstant] public const string Name = "Name";
            [InlineConstant] public const string Description = "Description";
            [InlineConstant] public const string ItemId = "ItemId";
            [InlineConstant] public const string TaxId = "TaxId";
            [InlineConstant] public const string Rate = "Rate";
            [InlineConstant] public const string Note = "Note";
            [InlineConstant] public const string ProjectId = "ProjectId";
            [InlineConstant] public const string OrganogramId = "OrganogramId";
            [InlineConstant] public const string ScopeId = "ScopeId";
            [InlineConstant] public const string CompanyId = "CompanyId";
            [InlineConstant] public const string StatusId = "StatusId";
            [InlineConstant] public const string ActiveOn = "ActiveOn";
            [InlineConstant] public const string InactiveOn = "InactiveOn";
            [InlineConstant] public const string IsActive = "IsActive";
            [InlineConstant] public const string DbId = "DbId";
            [InlineConstant] public const string CreatedBy = "CreatedBy";
            [InlineConstant] public const string CreatedOn = "CreatedOn";
            [InlineConstant] public const string CreatedPc = "CreatedPc";
            [InlineConstant] public const string UpdatedBy = "UpdatedBy";
            [InlineConstant] public const string UpdatedOn = "UpdatedOn";
            [InlineConstant] public const string UpdatedPc = "UpdatedPc";
            [InlineConstant] public const string DeletedBy = "DeletedBy";
            [InlineConstant] public const string DeletedOn = "DeletedOn";
            [InlineConstant] public const string DeletedPc = "DeletedPc";
            [InlineConstant] public const string IsDelete = "IsDelete";
            [InlineConstant] public const string ItemCode = "ItemCode";
            [InlineConstant] public const string ItemName = "ItemName";
            [InlineConstant] public const string ItemDescription = "ItemDescription";
            [InlineConstant] public const string ItemItemGroupId = "ItemItemGroupId";
            [InlineConstant] public const string ItemUomId = "ItemUomId";
            [InlineConstant] public const string ItemImageId = "ItemImageId";
            [InlineConstant] public const string ItemSpecificationId = "ItemSpecificationId";
            [InlineConstant] public const string ItemColorId = "ItemColorId";
            [InlineConstant] public const string ItemSizeId = "ItemSizeId";
            [InlineConstant] public const string ItemModelId = "ItemModelId";
            [InlineConstant] public const string ItemStyleId = "ItemStyleId";
            [InlineConstant] public const string ItemBrandId = "ItemBrandId";
            [InlineConstant] public const string ItemCountryId = "ItemCountryId";
            [InlineConstant] public const string ItemSeasonId = "ItemSeasonId";
            [InlineConstant] public const string ItemPurposeId = "ItemPurposeId";
            [InlineConstant] public const string ItemSupplierId = "ItemSupplierId";
            [InlineConstant] public const string ItemConditionId = "ItemConditionId";
            [InlineConstant] public const string ItemQualityId = "ItemQualityId";
            [InlineConstant] public const string ItemYear = "ItemYear";
            [InlineConstant] public const string ItemExpireDate = "ItemExpireDate";
            [InlineConstant] public const string ItemLifeTime = "ItemLifeTime";
            [InlineConstant] public const string ItemBarcode = "ItemBarcode";
            [InlineConstant] public const string ItemUnitWeight = "ItemUnitWeight";
            [InlineConstant] public const string ItemWeightUomId = "ItemWeightUomId";
            [InlineConstant] public const string ItemReorderLevel = "ItemReorderLevel";
            [InlineConstant] public const string ItemCostPrice = "ItemCostPrice";
            [InlineConstant] public const string ItemSellingPrice = "ItemSellingPrice";
            [InlineConstant] public const string ItemPromoPrice = "ItemPromoPrice";
            [InlineConstant] public const string ItemPromoStartDate = "ItemPromoStartDate";
            [InlineConstant] public const string ItemPromoEndDate = "ItemPromoEndDate";
            [InlineConstant] public const string ItemCommissionAmt = "ItemCommissionAmt";
            [InlineConstant] public const string ItemIsCommissionPercent = "ItemIsCommissionPercent";
            [InlineConstant] public const string ItemIsTaxInclude = "ItemIsTaxInclude";
            [InlineConstant] public const string ItemIsOverrideTax = "ItemIsOverrideTax";
            [InlineConstant] public const string ItemTax1 = "ItemTax1";
            [InlineConstant] public const string ItemTax2 = "ItemTax2";
            [InlineConstant] public const string ItemTax3 = "ItemTax3";
            [InlineConstant] public const string ItemTax4 = "ItemTax4";
            [InlineConstant] public const string ItemTax5 = "ItemTax5";
            [InlineConstant] public const string ItemTax1Rate = "ItemTax1Rate";
            [InlineConstant] public const string ItemTax2Rate = "ItemTax2Rate";
            [InlineConstant] public const string ItemTax3Rate = "ItemTax3Rate";
            [InlineConstant] public const string ItemTax4Rate = "ItemTax4Rate";
            [InlineConstant] public const string ItemTax5Rate = "ItemTax5Rate";
            [InlineConstant] public const string ItemDefaultQty = "ItemDefaultQty";
            [InlineConstant] public const string ItemDefaultLocationAtStore = "ItemDefaultLocationAtStore";
            [InlineConstant] public const string ItemNote = "ItemNote";
            [InlineConstant] public const string ItemProjectId = "ItemProjectId";
            [InlineConstant] public const string ItemOrganogramId = "ItemOrganogramId";
            [InlineConstant] public const string ItemScopeId = "ItemScopeId";
            [InlineConstant] public const string ItemCompanyId = "ItemCompanyId";
            [InlineConstant] public const string ItemStatusId = "ItemStatusId";
            [InlineConstant] public const string ItemActiveOn = "ItemActiveOn";
            [InlineConstant] public const string ItemInactiveOn = "ItemInactiveOn";
            [InlineConstant] public const string ItemIsActive = "ItemIsActive";
            [InlineConstant] public const string ItemDbId = "ItemDbId";
            [InlineConstant] public const string ItemCreatedBy = "ItemCreatedBy";
            [InlineConstant] public const string ItemCreatedOn = "ItemCreatedOn";
            [InlineConstant] public const string ItemCreatedPc = "ItemCreatedPc";
            [InlineConstant] public const string ItemUpdatedBy = "ItemUpdatedBy";
            [InlineConstant] public const string ItemUpdatedOn = "ItemUpdatedOn";
            [InlineConstant] public const string ItemUpdatedPc = "ItemUpdatedPc";
            [InlineConstant] public const string ItemDeletedBy = "ItemDeletedBy";
            [InlineConstant] public const string ItemDeletedOn = "ItemDeletedOn";
            [InlineConstant] public const string ItemDeletedPc = "ItemDeletedPc";
            [InlineConstant] public const string ItemIsDelete = "ItemIsDelete";
            [InlineConstant] public const string TaxCode = "TaxCode";
            [InlineConstant] public const string TaxName = "TaxName";
            [InlineConstant] public const string TaxDescription = "TaxDescription";
            [InlineConstant] public const string TaxRate = "TaxRate";
            [InlineConstant] public const string TaxIsDefault = "TaxIsDefault";
            [InlineConstant] public const string TaxNote = "TaxNote";
            [InlineConstant] public const string TaxProjectId = "TaxProjectId";
            [InlineConstant] public const string TaxOrganogramId = "TaxOrganogramId";
            [InlineConstant] public const string TaxScopeId = "TaxScopeId";
            [InlineConstant] public const string TaxCompanyId = "TaxCompanyId";
            [InlineConstant] public const string TaxStatusId = "TaxStatusId";
            [InlineConstant] public const string TaxActiveOn = "TaxActiveOn";
            [InlineConstant] public const string TaxInactiveOn = "TaxInactiveOn";
            [InlineConstant] public const string TaxIsActive = "TaxIsActive";
            [InlineConstant] public const string TaxDbId = "TaxDbId";
            [InlineConstant] public const string TaxCreatedBy = "TaxCreatedBy";
            [InlineConstant] public const string TaxCreatedOn = "TaxCreatedOn";
            [InlineConstant] public const string TaxCreatedPc = "TaxCreatedPc";
            [InlineConstant] public const string TaxUpdatedBy = "TaxUpdatedBy";
            [InlineConstant] public const string TaxUpdatedOn = "TaxUpdatedOn";
            [InlineConstant] public const string TaxUpdatedPc = "TaxUpdatedPc";
            [InlineConstant] public const string TaxDeletedBy = "TaxDeletedBy";
            [InlineConstant] public const string TaxDeletedOn = "TaxDeletedOn";
            [InlineConstant] public const string TaxDeletedPc = "TaxDeletedPc";
            [InlineConstant] public const string TaxIsDelete = "TaxIsDelete";
        }
    }
}