
namespace NERP.HR
{
    using Serenity;
    using Serenity.ComponentModel;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    [Imported, Serializable, PreserveMemberCase]
    public partial class EmployeeRow
    {
        [InlineConstant] public const string IdProperty = "Id";
        [InlineConstant] public const string NameProperty = "Code";
        [InlineConstant] public const string IsActiveProperty = "IsActive";
        [InlineConstant] public const string LocalTextPrefix = "HR.Employee";

        public Int32? Id { get; set; }
        public String Code { get; set; }
        public String Name { get; set; }
        public String Description { get; set; }
        public Int32? UserTypeId { get; set; }
        public Int32? UserGroupId { get; set; }
        public String FirstName { get; set; }
        public String MiddleName { get; set; }
        public String LastName { get; set; }
        public String FullName { get; set; }
        public Int32? ImageId { get; set; }
        public String Address1 { get; set; }
        public String Address2 { get; set; }
        public String Mobile { get; set; }
        public String Email { get; set; }
        public String DateOfBirth { get; set; }
        public String LoginName { get; set; }
        public String Password { get; set; }
        public Int16? IsTaxable { get; set; }
        public Decimal? CommissionRate { get; set; }
        public String Note { get; set; }
        public Int32? ProjectId { get; set; }
        public Int32? OrganogramId { get; set; }
        public Int32? ScopeId { get; set; }
        public Int32? CompanyId { get; set; }
        public Int32? StatusId { get; set; }
        public String ActiveOn { get; set; }
        public String InactiveOn { get; set; }
        public Int16? IsActive { get; set; }
        public Int32? DbId { get; set; }
        public Int32? CreatedBy { get; set; }
        public String CreatedOn { get; set; }
        //public String CreatedPc { get; set; }
        public Int32? UpdatedBy { get; set; }
        public String UpdatedOn { get; set; }
        //public String UpdatedPc { get; set; }
        public Int32? DeletedBy { get; set; }
        public String DeletedOn { get; set; }
        //public String DeletedPc { get; set; }
        public Int16? IsDelete { get; set; }
        public String UserGroupCode { get; set; }
        public String UserGroupName { get; set; }
        public String UserGroupDescription { get; set; }
        public String UserGroupNote { get; set; }
        public Int32? UserGroupProjectId { get; set; }
        public Int32? UserGroupOrganogramId { get; set; }
        public Int32? UserGroupScopeId { get; set; }
        public Int32? UserGroupCompanyId { get; set; }
        public Int32? UserGroupStatusId { get; set; }
        public String UserGroupActiveOn { get; set; }
        public String UserGroupInactiveOn { get; set; }
        public Int16? UserGroupIsActive { get; set; }
        public Int32? UserGroupDbId { get; set; }
        public Int32? UserGroupCreatedBy { get; set; }
        public String UserGroupCreatedOn { get; set; }
        public String UserGroupCreatedPc { get; set; }
        public Int32? UserGroupUpdatedBy { get; set; }
        public String UserGroupUpdatedOn { get; set; }
        public String UserGroupUpdatedPc { get; set; }
        public Int32? UserGroupDeletedBy { get; set; }
        public String UserGroupDeletedOn { get; set; }
        public String UserGroupDeletedPc { get; set; }
        public Int16? UserGroupIsDelete { get; set; }
        public String ImageCode { get; set; }
        public String ImageName { get; set; }
        public String ImageDescription { get; set; }
        public Int32? ImageImageTypeId { get; set; }
        public String ImagePath { get; set; }
        public Decimal? ImageSizeKb { get; set; }
        public Decimal? ImageWidePixel { get; set; }
        public Decimal? ImageHeightPixel { get; set; }
        public String ImageNote { get; set; }
        public Int32? ImageProjectId { get; set; }
        public Int32? ImageOrganogramId { get; set; }
        public Int32? ImageScopeId { get; set; }
        public Int32? ImageCompanyId { get; set; }
        public Int32? ImageStatusId { get; set; }
        public String ImageActiveOn { get; set; }
        public String ImageInactiveOn { get; set; }
        public Int16? ImageIsActive { get; set; }
        public Int32? ImageDbId { get; set; }
        public Int32? ImageCreatedBy { get; set; }
        public String ImageCreatedOn { get; set; }
        public String ImageCreatedPc { get; set; }
        public Int32? ImageUpdatedBy { get; set; }
        public String ImageUpdatedOn { get; set; }
        public String ImageUpdatedPc { get; set; }
        public Int32? ImageDeletedBy { get; set; }
        public String ImageDeletedOn { get; set; }
        public String ImageDeletedPc { get; set; }
        public Int16? ImageIsDelete { get; set; }
        public String ProjectCode { get; set; }
        public String ProjectName { get; set; }
        public String ProjectDescription { get; set; }
        public String ProjectNote { get; set; }
        public Int32? ProjectProjectId { get; set; }
        public Int32? ProjectOrganogramId { get; set; }
        public Int32? ProjectScopeId { get; set; }
        public Int32? ProjectCompanyId { get; set; }
        public Int32? ProjectStatusId { get; set; }
        public String ProjectActiveOn { get; set; }
        public String ProjectInactiveOn { get; set; }
        public Int16? ProjectIsActive { get; set; }
        public Int32? ProjectDbId { get; set; }
        public Int32? ProjectCreatedBy { get; set; }
        public String ProjectCreatedOn { get; set; }
        public String ProjectCreatedPc { get; set; }
        public Int32? ProjectUpdatedBy { get; set; }
        public String ProjectUpdatedOn { get; set; }
        public String ProjectUpdatedPc { get; set; }
        public Int32? ProjectDeletedBy { get; set; }
        public String ProjectDeletedOn { get; set; }
        public String ProjectDeletedPc { get; set; }
        public Int16? ProjectIsDelete { get; set; }
        public String OrganogramCode { get; set; }
        public String OrganogramName { get; set; }
        public String OrganogramDescription { get; set; }
        public Int32? OrganogramParentId { get; set; }
        public String OrganogramNote { get; set; }
        public Int32? OrganogramProjectId { get; set; }
        public Int32? OrganogramOrganogramId { get; set; }
        public Int32? OrganogramScopeId { get; set; }
        public Int32? OrganogramCompanyId { get; set; }
        public Int32? OrganogramStatusId { get; set; }
        public String OrganogramActiveOn { get; set; }
        public String OrganogramInactiveOn { get; set; }
        public Int16? OrganogramIsActive { get; set; }
        public Int32? OrganogramDbId { get; set; }
        public Int32? OrganogramCreatedBy { get; set; }
        public String OrganogramCreatedOn { get; set; }
        public String OrganogramCreatedPc { get; set; }
        public Int32? OrganogramUpdatedBy { get; set; }
        public String OrganogramUpdatedOn { get; set; }
        public String OrganogramUpdatedPc { get; set; }
        public Int32? OrganogramDeletedBy { get; set; }
        public String OrganogramDeletedOn { get; set; }
        public String OrganogramDeletedPc { get; set; }
        public Int16? OrganogramIsDelete { get; set; }
        public String CompanyCode { get; set; }
        public String CompanyName { get; set; }
        public String CompanyDescription { get; set; }
        public Int32? CompanyImageId { get; set; }
        public String CompanyNote { get; set; }
        public Int32? CompanyProjectId { get; set; }
        public Int32? CompanyOrganogramId { get; set; }
        public Int32? CompanyScopeId { get; set; }
        public Int32? CompanyCompanyId { get; set; }
        public Int32? CompanyStatusId { get; set; }
        public String CompanyActiveOn { get; set; }
        public String CompanyInactiveOn { get; set; }
        public Int16? CompanyIsActive { get; set; }
        public Int32? CompanyDbId { get; set; }
        public Int32? CompanyCreatedBy { get; set; }
        public String CompanyCreatedOn { get; set; }
        public String CompanyCreatedPc { get; set; }
        public Int32? CompanyUpdatedBy { get; set; }
        public String CompanyUpdatedOn { get; set; }
        public String CompanyUpdatedPc { get; set; }
        public Int32? CompanyDeletedBy { get; set; }
        public String CompanyDeletedOn { get; set; }
        public String CompanyDeletedPc { get; set; }
        public Int16? CompanyIsDelete { get; set; }

        [Imported, PreserveMemberCase]
        public static class Fields
        {
            [InlineConstant] public const string Id = "Id";
            [InlineConstant] public const string Code = "Code";
            [InlineConstant] public const string Name = "Name";
            [InlineConstant] public const string Description = "Description";
            [InlineConstant] public const string UserTypeId = "UserTypeId";
            [InlineConstant] public const string UserGroupId = "UserGroupId";
            [InlineConstant] public const string FirstName = "FirstName";
            [InlineConstant] public const string MiddleName = "MiddleName";
            [InlineConstant] public const string LastName = "LastName";
            [InlineConstant] public const string FullName = "FullName";
            [InlineConstant] public const string ImageId = "ImageId";
            [InlineConstant] public const string Address1 = "Address1";
            [InlineConstant] public const string Address2 = "Address2";
            [InlineConstant] public const string Mobile = "Mobile";
            [InlineConstant] public const string Email = "Email";
            [InlineConstant] public const string DateOfBirth = "DateOfBirth";
            [InlineConstant] public const string LoginName = "LoginName";
            [InlineConstant] public const string Password = "Password";
            [InlineConstant] public const string IsTaxable = "IsTaxable";
            [InlineConstant] public const string CommissionRate = "CommissionRate";
            [InlineConstant] public const string Note = "Note";
            [InlineConstant] public const string ProjectId = "ProjectId";
            [InlineConstant] public const string OrganogramId = "OrganogramId";
            [InlineConstant] public const string ScopeId = "ScopeId";
            [InlineConstant] public const string CompanyId = "CompanyId";
            [InlineConstant] public const string StatusId = "StatusId";
            [InlineConstant] public const string ActiveOn = "ActiveOn";
            [InlineConstant] public const string InactiveOn = "InactiveOn";
            [InlineConstant] public const string IsActive = "IsActive";
            [InlineConstant] public const string DbId = "DbId";
            [InlineConstant] public const string CreatedBy = "CreatedBy";
            [InlineConstant] public const string CreatedOn = "CreatedOn";
            [InlineConstant] public const string CreatedPc = "CreatedPc";
            [InlineConstant] public const string UpdatedBy = "UpdatedBy";
            [InlineConstant] public const string UpdatedOn = "UpdatedOn";
            [InlineConstant] public const string UpdatedPc = "UpdatedPc";
            [InlineConstant] public const string DeletedBy = "DeletedBy";
            [InlineConstant] public const string DeletedOn = "DeletedOn";
            [InlineConstant] public const string DeletedPc = "DeletedPc";
            [InlineConstant] public const string IsDelete = "IsDelete";
            [InlineConstant] public const string UserGroupCode = "UserGroupCode";
            [InlineConstant] public const string UserGroupName = "UserGroupName";
            [InlineConstant] public const string UserGroupDescription = "UserGroupDescription";
            [InlineConstant] public const string UserGroupNote = "UserGroupNote";
            [InlineConstant] public const string UserGroupProjectId = "UserGroupProjectId";
            [InlineConstant] public const string UserGroupOrganogramId = "UserGroupOrganogramId";
            [InlineConstant] public const string UserGroupScopeId = "UserGroupScopeId";
            [InlineConstant] public const string UserGroupCompanyId = "UserGroupCompanyId";
            [InlineConstant] public const string UserGroupStatusId = "UserGroupStatusId";
            [InlineConstant] public const string UserGroupActiveOn = "UserGroupActiveOn";
            [InlineConstant] public const string UserGroupInactiveOn = "UserGroupInactiveOn";
            [InlineConstant] public const string UserGroupIsActive = "UserGroupIsActive";
            [InlineConstant] public const string UserGroupDbId = "UserGroupDbId";
            [InlineConstant] public const string UserGroupCreatedBy = "UserGroupCreatedBy";
            [InlineConstant] public const string UserGroupCreatedOn = "UserGroupCreatedOn";
            [InlineConstant] public const string UserGroupCreatedPc = "UserGroupCreatedPc";
            [InlineConstant] public const string UserGroupUpdatedBy = "UserGroupUpdatedBy";
            [InlineConstant] public const string UserGroupUpdatedOn = "UserGroupUpdatedOn";
            [InlineConstant] public const string UserGroupUpdatedPc = "UserGroupUpdatedPc";
            [InlineConstant] public const string UserGroupDeletedBy = "UserGroupDeletedBy";
            [InlineConstant] public const string UserGroupDeletedOn = "UserGroupDeletedOn";
            [InlineConstant] public const string UserGroupDeletedPc = "UserGroupDeletedPc";
            [InlineConstant] public const string UserGroupIsDelete = "UserGroupIsDelete";
            [InlineConstant] public const string ImageCode = "ImageCode";
            [InlineConstant] public const string ImageName = "ImageName";
            [InlineConstant] public const string ImageDescription = "ImageDescription";
            [InlineConstant] public const string ImageImageTypeId = "ImageImageTypeId";
            [InlineConstant] public const string ImagePath = "ImagePath";
            [InlineConstant] public const string ImageSizeKb = "ImageSizeKb";
            [InlineConstant] public const string ImageWidePixel = "ImageWidePixel";
            [InlineConstant] public const string ImageHeightPixel = "ImageHeightPixel";
            [InlineConstant] public const string ImageNote = "ImageNote";
            [InlineConstant] public const string ImageProjectId = "ImageProjectId";
            [InlineConstant] public const string ImageOrganogramId = "ImageOrganogramId";
            [InlineConstant] public const string ImageScopeId = "ImageScopeId";
            [InlineConstant] public const string ImageCompanyId = "ImageCompanyId";
            [InlineConstant] public const string ImageStatusId = "ImageStatusId";
            [InlineConstant] public const string ImageActiveOn = "ImageActiveOn";
            [InlineConstant] public const string ImageInactiveOn = "ImageInactiveOn";
            [InlineConstant] public const string ImageIsActive = "ImageIsActive";
            [InlineConstant] public const string ImageDbId = "ImageDbId";
            [InlineConstant] public const string ImageCreatedBy = "ImageCreatedBy";
            [InlineConstant] public const string ImageCreatedOn = "ImageCreatedOn";
            [InlineConstant] public const string ImageCreatedPc = "ImageCreatedPc";
            [InlineConstant] public const string ImageUpdatedBy = "ImageUpdatedBy";
            [InlineConstant] public const string ImageUpdatedOn = "ImageUpdatedOn";
            [InlineConstant] public const string ImageUpdatedPc = "ImageUpdatedPc";
            [InlineConstant] public const string ImageDeletedBy = "ImageDeletedBy";
            [InlineConstant] public const string ImageDeletedOn = "ImageDeletedOn";
            [InlineConstant] public const string ImageDeletedPc = "ImageDeletedPc";
            [InlineConstant] public const string ImageIsDelete = "ImageIsDelete";
            [InlineConstant] public const string ProjectCode = "ProjectCode";
            [InlineConstant] public const string ProjectName = "ProjectName";
            [InlineConstant] public const string ProjectDescription = "ProjectDescription";
            [InlineConstant] public const string ProjectNote = "ProjectNote";
            [InlineConstant] public const string ProjectProjectId = "ProjectProjectId";
            [InlineConstant] public const string ProjectOrganogramId = "ProjectOrganogramId";
            [InlineConstant] public const string ProjectScopeId = "ProjectScopeId";
            [InlineConstant] public const string ProjectCompanyId = "ProjectCompanyId";
            [InlineConstant] public const string ProjectStatusId = "ProjectStatusId";
            [InlineConstant] public const string ProjectActiveOn = "ProjectActiveOn";
            [InlineConstant] public const string ProjectInactiveOn = "ProjectInactiveOn";
            [InlineConstant] public const string ProjectIsActive = "ProjectIsActive";
            [InlineConstant] public const string ProjectDbId = "ProjectDbId";
            [InlineConstant] public const string ProjectCreatedBy = "ProjectCreatedBy";
            [InlineConstant] public const string ProjectCreatedOn = "ProjectCreatedOn";
            [InlineConstant] public const string ProjectCreatedPc = "ProjectCreatedPc";
            [InlineConstant] public const string ProjectUpdatedBy = "ProjectUpdatedBy";
            [InlineConstant] public const string ProjectUpdatedOn = "ProjectUpdatedOn";
            [InlineConstant] public const string ProjectUpdatedPc = "ProjectUpdatedPc";
            [InlineConstant] public const string ProjectDeletedBy = "ProjectDeletedBy";
            [InlineConstant] public const string ProjectDeletedOn = "ProjectDeletedOn";
            [InlineConstant] public const string ProjectDeletedPc = "ProjectDeletedPc";
            [InlineConstant] public const string ProjectIsDelete = "ProjectIsDelete";
            [InlineConstant] public const string OrganogramCode = "OrganogramCode";
            [InlineConstant] public const string OrganogramName = "OrganogramName";
            [InlineConstant] public const string OrganogramDescription = "OrganogramDescription";
            [InlineConstant] public const string OrganogramParentId = "OrganogramParentId";
            [InlineConstant] public const string OrganogramNote = "OrganogramNote";
            [InlineConstant] public const string OrganogramProjectId = "OrganogramProjectId";
            [InlineConstant] public const string OrganogramOrganogramId = "OrganogramOrganogramId";
            [InlineConstant] public const string OrganogramScopeId = "OrganogramScopeId";
            [InlineConstant] public const string OrganogramCompanyId = "OrganogramCompanyId";
            [InlineConstant] public const string OrganogramStatusId = "OrganogramStatusId";
            [InlineConstant] public const string OrganogramActiveOn = "OrganogramActiveOn";
            [InlineConstant] public const string OrganogramInactiveOn = "OrganogramInactiveOn";
            [InlineConstant] public const string OrganogramIsActive = "OrganogramIsActive";
            [InlineConstant] public const string OrganogramDbId = "OrganogramDbId";
            [InlineConstant] public const string OrganogramCreatedBy = "OrganogramCreatedBy";
            [InlineConstant] public const string OrganogramCreatedOn = "OrganogramCreatedOn";
            [InlineConstant] public const string OrganogramCreatedPc = "OrganogramCreatedPc";
            [InlineConstant] public const string OrganogramUpdatedBy = "OrganogramUpdatedBy";
            [InlineConstant] public const string OrganogramUpdatedOn = "OrganogramUpdatedOn";
            [InlineConstant] public const string OrganogramUpdatedPc = "OrganogramUpdatedPc";
            [InlineConstant] public const string OrganogramDeletedBy = "OrganogramDeletedBy";
            [InlineConstant] public const string OrganogramDeletedOn = "OrganogramDeletedOn";
            [InlineConstant] public const string OrganogramDeletedPc = "OrganogramDeletedPc";
            [InlineConstant] public const string OrganogramIsDelete = "OrganogramIsDelete";
            [InlineConstant] public const string CompanyCode = "CompanyCode";
            [InlineConstant] public const string CompanyName = "CompanyName";
            [InlineConstant] public const string CompanyDescription = "CompanyDescription";
            [InlineConstant] public const string CompanyImageId = "CompanyImageId";
            [InlineConstant] public const string CompanyNote = "CompanyNote";
            [InlineConstant] public const string CompanyProjectId = "CompanyProjectId";
            [InlineConstant] public const string CompanyOrganogramId = "CompanyOrganogramId";
            [InlineConstant] public const string CompanyScopeId = "CompanyScopeId";
            [InlineConstant] public const string CompanyCompanyId = "CompanyCompanyId";
            [InlineConstant] public const string CompanyStatusId = "CompanyStatusId";
            [InlineConstant] public const string CompanyActiveOn = "CompanyActiveOn";
            [InlineConstant] public const string CompanyInactiveOn = "CompanyInactiveOn";
            [InlineConstant] public const string CompanyIsActive = "CompanyIsActive";
            [InlineConstant] public const string CompanyDbId = "CompanyDbId";
            [InlineConstant] public const string CompanyCreatedBy = "CompanyCreatedBy";
            [InlineConstant] public const string CompanyCreatedOn = "CompanyCreatedOn";
            [InlineConstant] public const string CompanyCreatedPc = "CompanyCreatedPc";
            [InlineConstant] public const string CompanyUpdatedBy = "CompanyUpdatedBy";
            [InlineConstant] public const string CompanyUpdatedOn = "CompanyUpdatedOn";
            [InlineConstant] public const string CompanyUpdatedPc = "CompanyUpdatedPc";
            [InlineConstant] public const string CompanyDeletedBy = "CompanyDeletedBy";
            [InlineConstant] public const string CompanyDeletedOn = "CompanyDeletedOn";
            [InlineConstant] public const string CompanyDeletedPc = "CompanyDeletedPc";
            [InlineConstant] public const string CompanyIsDelete = "CompanyIsDelete";
        }
    }
}