
namespace NERP.ItemTransaction
{
    using Serenity;
    using Serenity.ComponentModel;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    [Imported, Serializable, PreserveMemberCase]
    public partial class TransDetailRow
    {
        [InlineConstant] public const string IdProperty = "Id";
        [InlineConstant] public const string NameProperty = "Code";
        [InlineConstant] public const string IsActiveProperty = "IsActive";
        [InlineConstant] public const string LocalTextPrefix = "ItemTransaction.TransDetail";

        public Int32? Id { get; set; }
        public String Code { get; set; }
        public String Name { get; set; }
        public String Description { get; set; }
        public Int32? TransId { get; set; }
        public Int32? TransTypeId { get; set; }
        public Int32? ItemId { get; set; }
        public Int32? ItemDetailId { get; set; }
        public Int32? UomId { get; set; }
        public Decimal? Quantity { get; set; }
        public Decimal? SampleQty { get; set; }
        public Decimal? OverQty { get; set; }
        public Decimal? SubTotalQty { get; set; }
        public Decimal? MaxQty { get; set; }
        public Decimal? BalanceQty { get; set; }
        public Decimal? UnitPrice { get; set; }
        public Decimal? Amount { get; set; }
        public Decimal? TaxAmt { get; set; }
        public Decimal? DiscountAmt { get; set; }
        public Decimal? LineTotalAmt { get; set; }
        public Int16? IsReturn { get; set; }
        public Int16? IsOffer { get; set; }
        public Int32? OfferParentId { get; set; }
        public Int32? AccId { get; set; }
        public Int16? IsDebit { get; set; }
        public Decimal? DrAmt { get; set; }
        public Decimal? CrAmt { get; set; }
        public Int32? RefTypeId { get; set; }
        public Int32? RefId { get; set; }
        public Int32? RefDtlId { get; set; }
        public String RefCode { get; set; }
        public String RefNo { get; set; }
        public Int32? RefImgId { get; set; }
        public Int32? TransRefTypeId { get; set; }
        public Int32? TransRefId { get; set; }
        public Int32? TransRefDtlId { get; set; }
        public String TransRefCode { get; set; }
        public String TransRefNo { get; set; }
        public Int32? TransRefImgId { get; set; }
        public String Note { get; set; }
        public Int32? ProjectId { get; set; }
        public Int32? OrganogramId { get; set; }
        public Int32? ScopeId { get; set; }
        public Int32? CompanyId { get; set; }
        public Int32? StatusId { get; set; }
        public Int16? IsApproved { get; set; }
        public String ApprovedOn { get; set; }
        public String ActiveOn { get; set; }
        public String InactiveOn { get; set; }
        public Int16? IsActive { get; set; }
        public Int32? DbId { get; set; }
        public Int32? CreatedBy { get; set; }
        public String CreatedOn { get; set; }
        public String CreatedPc { get; set; }
        public Int32? UpdatedBy { get; set; }
        public String UpdatedOn { get; set; }
        public String UpdatedPc { get; set; }
        public Int32? DeletedBy { get; set; }
        public String DeletedOn { get; set; }
        public String DeletedPc { get; set; }
        public Int16? IsDelete { get; set; }
        public String TransCode { get; set; }
        public String TransName { get; set; }
        public String TransDescription { get; set; }
        public String TransDateTime { get; set; }
        public Int32? TransTransTypeId { get; set; }
        public String TransNote { get; set; }
        public Int32? TransProjectId { get; set; }
        public Int32? TransOrganogramId { get; set; }
        public Int32? TransScopeId { get; set; }
        public Int32? TransCompanyId { get; set; }
        public Int32? TransStatusId { get; set; }
        public String TransActiveOn { get; set; }
        public String TransInactiveOn { get; set; }
        public Int16? TransIsActive { get; set; }
        public Int32? TransDbId { get; set; }
        public Int32? TransCreatedBy { get; set; }
        public String TransCreatedOn { get; set; }
        public String TransCreatedPc { get; set; }
        public Int32? TransUpdatedBy { get; set; }
        public String TransUpdatedOn { get; set; }
        public String TransUpdatedPc { get; set; }
        public Int32? TransDeletedBy { get; set; }
        public String TransDeletedOn { get; set; }
        public String TransDeletedPc { get; set; }
        public Int16? TransIsDelete { get; set; }
        public String ItemCode { get; set; }
        public String ItemName { get; set; }
        public String ItemDescription { get; set; }
        public Int32? ItemItemGroupId { get; set; }
        public Int32? ItemUomId { get; set; }
        public Int32? ItemImageId { get; set; }
        public Int32? ItemSpecificationId { get; set; }
        public Int32? ItemColorId { get; set; }
        public Int32? ItemSizeId { get; set; }
        public Int32? ItemModelId { get; set; }
        public Int32? ItemStyleId { get; set; }
        public Int32? ItemBrandId { get; set; }
        public Int32? ItemCountryId { get; set; }
        public Int32? ItemSeasonId { get; set; }
        public Int32? ItemPurposeId { get; set; }
        public Int32? ItemSupplierId { get; set; }
        public Int32? ItemConditionId { get; set; }
        public Int32? ItemQualityId { get; set; }
        public Int32? ItemYear { get; set; }
        public String ItemExpireDate { get; set; }
        public Int32? ItemLifeTime { get; set; }
        public String ItemBarcode { get; set; }
        public Decimal? ItemUnitWeight { get; set; }
        public Int32? ItemWeightUomId { get; set; }
        public Decimal? ItemReorderLevel { get; set; }
        public Decimal? ItemCostPrice { get; set; }
        public Decimal? ItemSellingPrice { get; set; }
        public Decimal? ItemPromoPrice { get; set; }
        public String ItemPromoStartDate { get; set; }
        public String ItemPromoEndDate { get; set; }
        public Decimal? ItemCommissionAmt { get; set; }
        public Int16? ItemIsCommissionPercent { get; set; }
        public Int16? ItemIsTaxInclude { get; set; }
        public Int16? ItemIsOverrideTax { get; set; }
        public String ItemTax1 { get; set; }
        public String ItemTax2 { get; set; }
        public String ItemTax3 { get; set; }
        public String ItemTax4 { get; set; }
        public String ItemTax5 { get; set; }
        public Decimal? ItemTax1Rate { get; set; }
        public Decimal? ItemTax2Rate { get; set; }
        public Decimal? ItemTax3Rate { get; set; }
        public Decimal? ItemTax4Rate { get; set; }
        public Decimal? ItemTax5Rate { get; set; }
        public Decimal? ItemDefaultQty { get; set; }
        public String ItemDefaultLocationAtStore { get; set; }
        public String ItemNote { get; set; }
        public Int32? ItemProjectId { get; set; }
        public Int32? ItemOrganogramId { get; set; }
        public Int32? ItemScopeId { get; set; }
        public Int32? ItemCompanyId { get; set; }
        public Int32? ItemStatusId { get; set; }
        public String ItemActiveOn { get; set; }
        public String ItemInactiveOn { get; set; }
        public Int16? ItemIsActive { get; set; }
        public Int32? ItemDbId { get; set; }
        public Int32? ItemCreatedBy { get; set; }
        public String ItemCreatedOn { get; set; }
        public String ItemCreatedPc { get; set; }
        public Int32? ItemUpdatedBy { get; set; }
        public String ItemUpdatedOn { get; set; }
        public String ItemUpdatedPc { get; set; }
        public Int32? ItemDeletedBy { get; set; }
        public String ItemDeletedOn { get; set; }
        public String ItemDeletedPc { get; set; }
        public Int16? ItemIsDelete { get; set; }
        public String UomCode { get; set; }
        public String UomName { get; set; }
        public String UomDescription { get; set; }
        public Int32? UomUomTyepId { get; set; }
        public Decimal? UomRateToStandard { get; set; }
        public String UomNote { get; set; }
        public Int32? UomProjectId { get; set; }
        public Int32? UomOrganogramId { get; set; }
        public Int32? UomScopeId { get; set; }
        public Int32? UomCompanyId { get; set; }
        public Int32? UomStatusId { get; set; }
        public String UomActiveOn { get; set; }
        public String UomInactiveOn { get; set; }
        public Int16? UomIsActive { get; set; }
        public Int32? UomDbId { get; set; }
        public Int32? UomCreatedBy { get; set; }
        public String UomCreatedOn { get; set; }
        public String UomCreatedPc { get; set; }
        public Int32? UomUpdatedBy { get; set; }
        public String UomUpdatedOn { get; set; }
        public String UomUpdatedPc { get; set; }
        public Int32? UomDeletedBy { get; set; }
        public String UomDeletedOn { get; set; }
        public String UomDeletedPc { get; set; }
        public Int16? UomIsDelete { get; set; }

        [Imported, PreserveMemberCase]
        public static class Fields
        {
            [InlineConstant] public const string Id = "Id";
            [InlineConstant] public const string Code = "Code";
            [InlineConstant] public const string Name = "Name";
            [InlineConstant] public const string Description = "Description";
            [InlineConstant] public const string TransId = "TransId";
            [InlineConstant] public const string TransTypeId = "TransTypeId";
            [InlineConstant] public const string ItemId = "ItemId";
            [InlineConstant] public const string ItemDetailId = "ItemDetailId";
            [InlineConstant] public const string UomId = "UomId";
            [InlineConstant] public const string Quantity = "Quantity";
            [InlineConstant] public const string SampleQty = "SampleQty";
            [InlineConstant] public const string OverQty = "OverQty";
            [InlineConstant] public const string SubTotalQty = "SubTotalQty";
            [InlineConstant] public const string MaxQty = "MaxQty";
            [InlineConstant] public const string BalanceQty = "BalanceQty";
            [InlineConstant] public const string UnitPrice = "UnitPrice";
            [InlineConstant] public const string Amount = "Amount";
            [InlineConstant] public const string TaxAmt = "TaxAmt";
            [InlineConstant] public const string DiscountAmt = "DiscountAmt";
            [InlineConstant] public const string LineTotalAmt = "LineTotalAmt";
            [InlineConstant] public const string IsReturn = "IsReturn";
            [InlineConstant] public const string IsOffer = "IsOffer";
            [InlineConstant] public const string OfferParentId = "OfferParentId";
            [InlineConstant] public const string AccId = "AccId";
            [InlineConstant] public const string IsDebit = "IsDebit";
            [InlineConstant] public const string DrAmt = "DrAmt";
            [InlineConstant] public const string CrAmt = "CrAmt";
            [InlineConstant] public const string RefTypeId = "RefTypeId";
            [InlineConstant] public const string RefId = "RefId";
            [InlineConstant] public const string RefDtlId = "RefDtlId";
            [InlineConstant] public const string RefCode = "RefCode";
            [InlineConstant] public const string RefNo = "RefNo";
            [InlineConstant] public const string RefImgId = "RefImgId";
            [InlineConstant] public const string TransRefTypeId = "TransRefTypeId";
            [InlineConstant] public const string TransRefId = "TransRefId";
            [InlineConstant] public const string TransRefDtlId = "TransRefDtlId";
            [InlineConstant] public const string TransRefCode = "TransRefCode";
            [InlineConstant] public const string TransRefNo = "TransRefNo";
            [InlineConstant] public const string TransRefImgId = "TransRefImgId";
            [InlineConstant] public const string Note = "Note";
            [InlineConstant] public const string ProjectId = "ProjectId";
            [InlineConstant] public const string OrganogramId = "OrganogramId";
            [InlineConstant] public const string ScopeId = "ScopeId";
            [InlineConstant] public const string CompanyId = "CompanyId";
            [InlineConstant] public const string StatusId = "StatusId";
            [InlineConstant] public const string IsApproved = "IsApproved";
            [InlineConstant] public const string ApprovedOn = "ApprovedOn";
            [InlineConstant] public const string ActiveOn = "ActiveOn";
            [InlineConstant] public const string InactiveOn = "InactiveOn";
            [InlineConstant] public const string IsActive = "IsActive";
            [InlineConstant] public const string DbId = "DbId";
            [InlineConstant] public const string CreatedBy = "CreatedBy";
            [InlineConstant] public const string CreatedOn = "CreatedOn";
            [InlineConstant] public const string CreatedPc = "CreatedPc";
            [InlineConstant] public const string UpdatedBy = "UpdatedBy";
            [InlineConstant] public const string UpdatedOn = "UpdatedOn";
            [InlineConstant] public const string UpdatedPc = "UpdatedPc";
            [InlineConstant] public const string DeletedBy = "DeletedBy";
            [InlineConstant] public const string DeletedOn = "DeletedOn";
            [InlineConstant] public const string DeletedPc = "DeletedPc";
            [InlineConstant] public const string IsDelete = "IsDelete";
            [InlineConstant] public const string TransCode = "TransCode";
            [InlineConstant] public const string TransName = "TransName";
            [InlineConstant] public const string TransDescription = "TransDescription";
            [InlineConstant] public const string TransDateTime = "TransDateTime";
            [InlineConstant] public const string TransTransTypeId = "TransTransTypeId";
            [InlineConstant] public const string TransNote = "TransNote";
            [InlineConstant] public const string TransProjectId = "TransProjectId";
            [InlineConstant] public const string TransOrganogramId = "TransOrganogramId";
            [InlineConstant] public const string TransScopeId = "TransScopeId";
            [InlineConstant] public const string TransCompanyId = "TransCompanyId";
            [InlineConstant] public const string TransStatusId = "TransStatusId";
            [InlineConstant] public const string TransActiveOn = "TransActiveOn";
            [InlineConstant] public const string TransInactiveOn = "TransInactiveOn";
            [InlineConstant] public const string TransIsActive = "TransIsActive";
            [InlineConstant] public const string TransDbId = "TransDbId";
            [InlineConstant] public const string TransCreatedBy = "TransCreatedBy";
            [InlineConstant] public const string TransCreatedOn = "TransCreatedOn";
            [InlineConstant] public const string TransCreatedPc = "TransCreatedPc";
            [InlineConstant] public const string TransUpdatedBy = "TransUpdatedBy";
            [InlineConstant] public const string TransUpdatedOn = "TransUpdatedOn";
            [InlineConstant] public const string TransUpdatedPc = "TransUpdatedPc";
            [InlineConstant] public const string TransDeletedBy = "TransDeletedBy";
            [InlineConstant] public const string TransDeletedOn = "TransDeletedOn";
            [InlineConstant] public const string TransDeletedPc = "TransDeletedPc";
            [InlineConstant] public const string TransIsDelete = "TransIsDelete";
            [InlineConstant] public const string ItemCode = "ItemCode";
            [InlineConstant] public const string ItemName = "ItemName";
            [InlineConstant] public const string ItemDescription = "ItemDescription";
            [InlineConstant] public const string ItemItemGroupId = "ItemItemGroupId";
            [InlineConstant] public const string ItemUomId = "ItemUomId";
            [InlineConstant] public const string ItemImageId = "ItemImageId";
            [InlineConstant] public const string ItemSpecificationId = "ItemSpecificationId";
            [InlineConstant] public const string ItemColorId = "ItemColorId";
            [InlineConstant] public const string ItemSizeId = "ItemSizeId";
            [InlineConstant] public const string ItemModelId = "ItemModelId";
            [InlineConstant] public const string ItemStyleId = "ItemStyleId";
            [InlineConstant] public const string ItemBrandId = "ItemBrandId";
            [InlineConstant] public const string ItemCountryId = "ItemCountryId";
            [InlineConstant] public const string ItemSeasonId = "ItemSeasonId";
            [InlineConstant] public const string ItemPurposeId = "ItemPurposeId";
            [InlineConstant] public const string ItemSupplierId = "ItemSupplierId";
            [InlineConstant] public const string ItemConditionId = "ItemConditionId";
            [InlineConstant] public const string ItemQualityId = "ItemQualityId";
            [InlineConstant] public const string ItemYear = "ItemYear";
            [InlineConstant] public const string ItemExpireDate = "ItemExpireDate";
            [InlineConstant] public const string ItemLifeTime = "ItemLifeTime";
            [InlineConstant] public const string ItemBarcode = "ItemBarcode";
            [InlineConstant] public const string ItemUnitWeight = "ItemUnitWeight";
            [InlineConstant] public const string ItemWeightUomId = "ItemWeightUomId";
            [InlineConstant] public const string ItemReorderLevel = "ItemReorderLevel";
            [InlineConstant] public const string ItemCostPrice = "ItemCostPrice";
            [InlineConstant] public const string ItemSellingPrice = "ItemSellingPrice";
            [InlineConstant] public const string ItemPromoPrice = "ItemPromoPrice";
            [InlineConstant] public const string ItemPromoStartDate = "ItemPromoStartDate";
            [InlineConstant] public const string ItemPromoEndDate = "ItemPromoEndDate";
            [InlineConstant] public const string ItemCommissionAmt = "ItemCommissionAmt";
            [InlineConstant] public const string ItemIsCommissionPercent = "ItemIsCommissionPercent";
            [InlineConstant] public const string ItemIsTaxInclude = "ItemIsTaxInclude";
            [InlineConstant] public const string ItemIsOverrideTax = "ItemIsOverrideTax";
            [InlineConstant] public const string ItemTax1 = "ItemTax1";
            [InlineConstant] public const string ItemTax2 = "ItemTax2";
            [InlineConstant] public const string ItemTax3 = "ItemTax3";
            [InlineConstant] public const string ItemTax4 = "ItemTax4";
            [InlineConstant] public const string ItemTax5 = "ItemTax5";
            [InlineConstant] public const string ItemTax1Rate = "ItemTax1Rate";
            [InlineConstant] public const string ItemTax2Rate = "ItemTax2Rate";
            [InlineConstant] public const string ItemTax3Rate = "ItemTax3Rate";
            [InlineConstant] public const string ItemTax4Rate = "ItemTax4Rate";
            [InlineConstant] public const string ItemTax5Rate = "ItemTax5Rate";
            [InlineConstant] public const string ItemDefaultQty = "ItemDefaultQty";
            [InlineConstant] public const string ItemDefaultLocationAtStore = "ItemDefaultLocationAtStore";
            [InlineConstant] public const string ItemNote = "ItemNote";
            [InlineConstant] public const string ItemProjectId = "ItemProjectId";
            [InlineConstant] public const string ItemOrganogramId = "ItemOrganogramId";
            [InlineConstant] public const string ItemScopeId = "ItemScopeId";
            [InlineConstant] public const string ItemCompanyId = "ItemCompanyId";
            [InlineConstant] public const string ItemStatusId = "ItemStatusId";
            [InlineConstant] public const string ItemActiveOn = "ItemActiveOn";
            [InlineConstant] public const string ItemInactiveOn = "ItemInactiveOn";
            [InlineConstant] public const string ItemIsActive = "ItemIsActive";
            [InlineConstant] public const string ItemDbId = "ItemDbId";
            [InlineConstant] public const string ItemCreatedBy = "ItemCreatedBy";
            [InlineConstant] public const string ItemCreatedOn = "ItemCreatedOn";
            [InlineConstant] public const string ItemCreatedPc = "ItemCreatedPc";
            [InlineConstant] public const string ItemUpdatedBy = "ItemUpdatedBy";
            [InlineConstant] public const string ItemUpdatedOn = "ItemUpdatedOn";
            [InlineConstant] public const string ItemUpdatedPc = "ItemUpdatedPc";
            [InlineConstant] public const string ItemDeletedBy = "ItemDeletedBy";
            [InlineConstant] public const string ItemDeletedOn = "ItemDeletedOn";
            [InlineConstant] public const string ItemDeletedPc = "ItemDeletedPc";
            [InlineConstant] public const string ItemIsDelete = "ItemIsDelete";
            [InlineConstant] public const string UomCode = "UomCode";
            [InlineConstant] public const string UomName = "UomName";
            [InlineConstant] public const string UomDescription = "UomDescription";
            [InlineConstant] public const string UomUomTyepId = "UomUomTyepId";
            [InlineConstant] public const string UomRateToStandard = "UomRateToStandard";
            [InlineConstant] public const string UomNote = "UomNote";
            [InlineConstant] public const string UomProjectId = "UomProjectId";
            [InlineConstant] public const string UomOrganogramId = "UomOrganogramId";
            [InlineConstant] public const string UomScopeId = "UomScopeId";
            [InlineConstant] public const string UomCompanyId = "UomCompanyId";
            [InlineConstant] public const string UomStatusId = "UomStatusId";
            [InlineConstant] public const string UomActiveOn = "UomActiveOn";
            [InlineConstant] public const string UomInactiveOn = "UomInactiveOn";
            [InlineConstant] public const string UomIsActive = "UomIsActive";
            [InlineConstant] public const string UomDbId = "UomDbId";
            [InlineConstant] public const string UomCreatedBy = "UomCreatedBy";
            [InlineConstant] public const string UomCreatedOn = "UomCreatedOn";
            [InlineConstant] public const string UomCreatedPc = "UomCreatedPc";
            [InlineConstant] public const string UomUpdatedBy = "UomUpdatedBy";
            [InlineConstant] public const string UomUpdatedOn = "UomUpdatedOn";
            [InlineConstant] public const string UomUpdatedPc = "UomUpdatedPc";
            [InlineConstant] public const string UomDeletedBy = "UomDeletedBy";
            [InlineConstant] public const string UomDeletedOn = "UomDeletedOn";
            [InlineConstant] public const string UomDeletedPc = "UomDeletedPc";
            [InlineConstant] public const string UomIsDelete = "UomIsDelete";
        }
    }
}