
namespace NERP.ItemTransaction
{
    using Serenity;
    using Serenity.ComponentModel;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    [Imported, Serializable, PreserveMemberCase]
    public partial class TransTaxRow
    {
        [InlineConstant] public const string IdProperty = "Id";
        [InlineConstant] public const string NameProperty = "Code";
        [InlineConstant] public const string IsActiveProperty = "IsActive";
        [InlineConstant] public const string LocalTextPrefix = "ItemTransaction.TransTax";

        public Int32? Id { get; set; }
        public String Code { get; set; }
        public String Name { get; set; }
        public String Description { get; set; }
        public Int32? TransId { get; set; }
        public Int32? TransDetailId { get; set; }
        public Int32? TaxId { get; set; }
        public Decimal? Rate { get; set; }
        public String Note { get; set; }
        public Int32? ProjectId { get; set; }
        public Int32? OrganogramId { get; set; }
        public Int32? ScopeId { get; set; }
        public Int32? CompanyId { get; set; }
        public Int32? StatusId { get; set; }
        public String ActiveOn { get; set; }
        public String InactiveOn { get; set; }
        public Int16? IsActive { get; set; }
        public Int32? DbId { get; set; }
        public Int32? CreatedBy { get; set; }
        public String CreatedOn { get; set; }
        public String CreatedPc { get; set; }
        public Int32? UpdatedBy { get; set; }
        public String UpdatedOn { get; set; }
        public String UpdatedPc { get; set; }
        public Int32? DeletedBy { get; set; }
        public String DeletedOn { get; set; }
        public String DeletedPc { get; set; }
        public Int16? IsDelete { get; set; }
        public String TransCode { get; set; }
        public String TransName { get; set; }
        public String TransDescription { get; set; }
        public String TransDateTime { get; set; }
        public Int32? TransTransTypeId { get; set; }
        public String TransNote { get; set; }
        public Int32? TransProjectId { get; set; }
        public Int32? TransOrganogramId { get; set; }
        public Int32? TransScopeId { get; set; }
        public Int32? TransCompanyId { get; set; }
        public Int32? TransStatusId { get; set; }
        public String TransActiveOn { get; set; }
        public String TransInactiveOn { get; set; }
        public Int16? TransIsActive { get; set; }
        public Int32? TransDbId { get; set; }
        public Int32? TransCreatedBy { get; set; }
        public String TransCreatedOn { get; set; }
        public String TransCreatedPc { get; set; }
        public Int32? TransUpdatedBy { get; set; }
        public String TransUpdatedOn { get; set; }
        public String TransUpdatedPc { get; set; }
        public Int32? TransDeletedBy { get; set; }
        public String TransDeletedOn { get; set; }
        public String TransDeletedPc { get; set; }
        public Int16? TransIsDelete { get; set; }
        public String TransDetailCode { get; set; }
        public String TransDetailName { get; set; }
        public String TransDetailDescription { get; set; }
        public Int32? TransDetailTransId { get; set; }
        public Int32? TransDetailTransTypeId { get; set; }
        public Int32? TransDetailItemId { get; set; }
        public Int32? TransDetailItemDetailId { get; set; }
        public Int32? TransDetailUomId { get; set; }
        public Decimal? TransDetailQuantity { get; set; }
        public Decimal? TransDetailSampleQty { get; set; }
        public Decimal? TransDetailOverQty { get; set; }
        public Decimal? TransDetailSubTotalQty { get; set; }
        public Decimal? TransDetailMaxQty { get; set; }
        public Decimal? TransDetailBalanceQty { get; set; }
        public Decimal? TransDetailUnitPrice { get; set; }
        public Decimal? TransDetailAmount { get; set; }
        public Decimal? TransDetailTaxAmt { get; set; }
        public Decimal? TransDetailDiscountAmt { get; set; }
        public Decimal? TransDetailLineTotalAmt { get; set; }
        public Int16? TransDetailIsReturn { get; set; }
        public Int16? TransDetailIsOffer { get; set; }
        public Int32? TransDetailOfferParentId { get; set; }
        public Int32? TransDetailAccId { get; set; }
        public Int16? TransDetailIsDebit { get; set; }
        public Decimal? TransDetailDrAmt { get; set; }
        public Decimal? TransDetailCrAmt { get; set; }
        public Int32? TransDetailRefTypeId { get; set; }
        public Int32? TransDetailRefId { get; set; }
        public Int32? TransDetailRefDtlId { get; set; }
        public String TransDetailRefCode { get; set; }
        public String TransDetailRefNo { get; set; }
        public Int32? TransDetailRefImgId { get; set; }
        public Int32? TransDetailTransRefTypeId { get; set; }
        public Int32? TransDetailTransRefId { get; set; }
        public Int32? TransDetailTransRefDtlId { get; set; }
        public String TransDetailTransRefCode { get; set; }
        public String TransDetailTransRefNo { get; set; }
        public Int32? TransDetailTransRefImgId { get; set; }
        public String TransDetailNote { get; set; }
        public Int32? TransDetailProjectId { get; set; }
        public Int32? TransDetailOrganogramId { get; set; }
        public Int32? TransDetailScopeId { get; set; }
        public Int32? TransDetailCompanyId { get; set; }
        public Int32? TransDetailStatusId { get; set; }
        public Int16? TransDetailIsApproved { get; set; }
        public String TransDetailApprovedOn { get; set; }
        public String TransDetailActiveOn { get; set; }
        public String TransDetailInactiveOn { get; set; }
        public Int16? TransDetailIsActive { get; set; }
        public Int32? TransDetailDbId { get; set; }
        public Int32? TransDetailCreatedBy { get; set; }
        public String TransDetailCreatedOn { get; set; }
        public String TransDetailCreatedPc { get; set; }
        public Int32? TransDetailUpdatedBy { get; set; }
        public String TransDetailUpdatedOn { get; set; }
        public String TransDetailUpdatedPc { get; set; }
        public Int32? TransDetailDeletedBy { get; set; }
        public String TransDetailDeletedOn { get; set; }
        public String TransDetailDeletedPc { get; set; }
        public Int16? TransDetailIsDelete { get; set; }
        public String TaxCode { get; set; }
        public String TaxName { get; set; }
        public String TaxDescription { get; set; }
        public Decimal? TaxRate { get; set; }
        public Int16? TaxIsDefault { get; set; }
        public String TaxNote { get; set; }
        public Int32? TaxProjectId { get; set; }
        public Int32? TaxOrganogramId { get; set; }
        public Int32? TaxScopeId { get; set; }
        public Int32? TaxCompanyId { get; set; }
        public Int32? TaxStatusId { get; set; }
        public String TaxActiveOn { get; set; }
        public String TaxInactiveOn { get; set; }
        public Int16? TaxIsActive { get; set; }
        public Int32? TaxDbId { get; set; }
        public Int32? TaxCreatedBy { get; set; }
        public String TaxCreatedOn { get; set; }
        public String TaxCreatedPc { get; set; }
        public Int32? TaxUpdatedBy { get; set; }
        public String TaxUpdatedOn { get; set; }
        public String TaxUpdatedPc { get; set; }
        public Int32? TaxDeletedBy { get; set; }
        public String TaxDeletedOn { get; set; }
        public String TaxDeletedPc { get; set; }
        public Int16? TaxIsDelete { get; set; }

        [Imported, PreserveMemberCase]
        public static class Fields
        {
            [InlineConstant] public const string Id = "Id";
            [InlineConstant] public const string Code = "Code";
            [InlineConstant] public const string Name = "Name";
            [InlineConstant] public const string Description = "Description";
            [InlineConstant] public const string TransId = "TransId";
            [InlineConstant] public const string TransDetailId = "TransDetailId";
            [InlineConstant] public const string TaxId = "TaxId";
            [InlineConstant] public const string Rate = "Rate";
            [InlineConstant] public const string Note = "Note";
            [InlineConstant] public const string ProjectId = "ProjectId";
            [InlineConstant] public const string OrganogramId = "OrganogramId";
            [InlineConstant] public const string ScopeId = "ScopeId";
            [InlineConstant] public const string CompanyId = "CompanyId";
            [InlineConstant] public const string StatusId = "StatusId";
            [InlineConstant] public const string ActiveOn = "ActiveOn";
            [InlineConstant] public const string InactiveOn = "InactiveOn";
            [InlineConstant] public const string IsActive = "IsActive";
            [InlineConstant] public const string DbId = "DbId";
            [InlineConstant] public const string CreatedBy = "CreatedBy";
            [InlineConstant] public const string CreatedOn = "CreatedOn";
            [InlineConstant] public const string CreatedPc = "CreatedPc";
            [InlineConstant] public const string UpdatedBy = "UpdatedBy";
            [InlineConstant] public const string UpdatedOn = "UpdatedOn";
            [InlineConstant] public const string UpdatedPc = "UpdatedPc";
            [InlineConstant] public const string DeletedBy = "DeletedBy";
            [InlineConstant] public const string DeletedOn = "DeletedOn";
            [InlineConstant] public const string DeletedPc = "DeletedPc";
            [InlineConstant] public const string IsDelete = "IsDelete";
            [InlineConstant] public const string TransCode = "TransCode";
            [InlineConstant] public const string TransName = "TransName";
            [InlineConstant] public const string TransDescription = "TransDescription";
            [InlineConstant] public const string TransDateTime = "TransDateTime";
            [InlineConstant] public const string TransTransTypeId = "TransTransTypeId";
            [InlineConstant] public const string TransNote = "TransNote";
            [InlineConstant] public const string TransProjectId = "TransProjectId";
            [InlineConstant] public const string TransOrganogramId = "TransOrganogramId";
            [InlineConstant] public const string TransScopeId = "TransScopeId";
            [InlineConstant] public const string TransCompanyId = "TransCompanyId";
            [InlineConstant] public const string TransStatusId = "TransStatusId";
            [InlineConstant] public const string TransActiveOn = "TransActiveOn";
            [InlineConstant] public const string TransInactiveOn = "TransInactiveOn";
            [InlineConstant] public const string TransIsActive = "TransIsActive";
            [InlineConstant] public const string TransDbId = "TransDbId";
            [InlineConstant] public const string TransCreatedBy = "TransCreatedBy";
            [InlineConstant] public const string TransCreatedOn = "TransCreatedOn";
            [InlineConstant] public const string TransCreatedPc = "TransCreatedPc";
            [InlineConstant] public const string TransUpdatedBy = "TransUpdatedBy";
            [InlineConstant] public const string TransUpdatedOn = "TransUpdatedOn";
            [InlineConstant] public const string TransUpdatedPc = "TransUpdatedPc";
            [InlineConstant] public const string TransDeletedBy = "TransDeletedBy";
            [InlineConstant] public const string TransDeletedOn = "TransDeletedOn";
            [InlineConstant] public const string TransDeletedPc = "TransDeletedPc";
            [InlineConstant] public const string TransIsDelete = "TransIsDelete";
            [InlineConstant] public const string TransDetailCode = "TransDetailCode";
            [InlineConstant] public const string TransDetailName = "TransDetailName";
            [InlineConstant] public const string TransDetailDescription = "TransDetailDescription";
            [InlineConstant] public const string TransDetailTransId = "TransDetailTransId";
            [InlineConstant] public const string TransDetailTransTypeId = "TransDetailTransTypeId";
            [InlineConstant] public const string TransDetailItemId = "TransDetailItemId";
            [InlineConstant] public const string TransDetailItemDetailId = "TransDetailItemDetailId";
            [InlineConstant] public const string TransDetailUomId = "TransDetailUomId";
            [InlineConstant] public const string TransDetailQuantity = "TransDetailQuantity";
            [InlineConstant] public const string TransDetailSampleQty = "TransDetailSampleQty";
            [InlineConstant] public const string TransDetailOverQty = "TransDetailOverQty";
            [InlineConstant] public const string TransDetailSubTotalQty = "TransDetailSubTotalQty";
            [InlineConstant] public const string TransDetailMaxQty = "TransDetailMaxQty";
            [InlineConstant] public const string TransDetailBalanceQty = "TransDetailBalanceQty";
            [InlineConstant] public const string TransDetailUnitPrice = "TransDetailUnitPrice";
            [InlineConstant] public const string TransDetailAmount = "TransDetailAmount";
            [InlineConstant] public const string TransDetailTaxAmt = "TransDetailTaxAmt";
            [InlineConstant] public const string TransDetailDiscountAmt = "TransDetailDiscountAmt";
            [InlineConstant] public const string TransDetailLineTotalAmt = "TransDetailLineTotalAmt";
            [InlineConstant] public const string TransDetailIsReturn = "TransDetailIsReturn";
            [InlineConstant] public const string TransDetailIsOffer = "TransDetailIsOffer";
            [InlineConstant] public const string TransDetailOfferParentId = "TransDetailOfferParentId";
            [InlineConstant] public const string TransDetailAccId = "TransDetailAccId";
            [InlineConstant] public const string TransDetailIsDebit = "TransDetailIsDebit";
            [InlineConstant] public const string TransDetailDrAmt = "TransDetailDrAmt";
            [InlineConstant] public const string TransDetailCrAmt = "TransDetailCrAmt";
            [InlineConstant] public const string TransDetailRefTypeId = "TransDetailRefTypeId";
            [InlineConstant] public const string TransDetailRefId = "TransDetailRefId";
            [InlineConstant] public const string TransDetailRefDtlId = "TransDetailRefDtlId";
            [InlineConstant] public const string TransDetailRefCode = "TransDetailRefCode";
            [InlineConstant] public const string TransDetailRefNo = "TransDetailRefNo";
            [InlineConstant] public const string TransDetailRefImgId = "TransDetailRefImgId";
            [InlineConstant] public const string TransDetailTransRefTypeId = "TransDetailTransRefTypeId";
            [InlineConstant] public const string TransDetailTransRefId = "TransDetailTransRefId";
            [InlineConstant] public const string TransDetailTransRefDtlId = "TransDetailTransRefDtlId";
            [InlineConstant] public const string TransDetailTransRefCode = "TransDetailTransRefCode";
            [InlineConstant] public const string TransDetailTransRefNo = "TransDetailTransRefNo";
            [InlineConstant] public const string TransDetailTransRefImgId = "TransDetailTransRefImgId";
            [InlineConstant] public const string TransDetailNote = "TransDetailNote";
            [InlineConstant] public const string TransDetailProjectId = "TransDetailProjectId";
            [InlineConstant] public const string TransDetailOrganogramId = "TransDetailOrganogramId";
            [InlineConstant] public const string TransDetailScopeId = "TransDetailScopeId";
            [InlineConstant] public const string TransDetailCompanyId = "TransDetailCompanyId";
            [InlineConstant] public const string TransDetailStatusId = "TransDetailStatusId";
            [InlineConstant] public const string TransDetailIsApproved = "TransDetailIsApproved";
            [InlineConstant] public const string TransDetailApprovedOn = "TransDetailApprovedOn";
            [InlineConstant] public const string TransDetailActiveOn = "TransDetailActiveOn";
            [InlineConstant] public const string TransDetailInactiveOn = "TransDetailInactiveOn";
            [InlineConstant] public const string TransDetailIsActive = "TransDetailIsActive";
            [InlineConstant] public const string TransDetailDbId = "TransDetailDbId";
            [InlineConstant] public const string TransDetailCreatedBy = "TransDetailCreatedBy";
            [InlineConstant] public const string TransDetailCreatedOn = "TransDetailCreatedOn";
            [InlineConstant] public const string TransDetailCreatedPc = "TransDetailCreatedPc";
            [InlineConstant] public const string TransDetailUpdatedBy = "TransDetailUpdatedBy";
            [InlineConstant] public const string TransDetailUpdatedOn = "TransDetailUpdatedOn";
            [InlineConstant] public const string TransDetailUpdatedPc = "TransDetailUpdatedPc";
            [InlineConstant] public const string TransDetailDeletedBy = "TransDetailDeletedBy";
            [InlineConstant] public const string TransDetailDeletedOn = "TransDetailDeletedOn";
            [InlineConstant] public const string TransDetailDeletedPc = "TransDetailDeletedPc";
            [InlineConstant] public const string TransDetailIsDelete = "TransDetailIsDelete";
            [InlineConstant] public const string TaxCode = "TaxCode";
            [InlineConstant] public const string TaxName = "TaxName";
            [InlineConstant] public const string TaxDescription = "TaxDescription";
            [InlineConstant] public const string TaxRate = "TaxRate";
            [InlineConstant] public const string TaxIsDefault = "TaxIsDefault";
            [InlineConstant] public const string TaxNote = "TaxNote";
            [InlineConstant] public const string TaxProjectId = "TaxProjectId";
            [InlineConstant] public const string TaxOrganogramId = "TaxOrganogramId";
            [InlineConstant] public const string TaxScopeId = "TaxScopeId";
            [InlineConstant] public const string TaxCompanyId = "TaxCompanyId";
            [InlineConstant] public const string TaxStatusId = "TaxStatusId";
            [InlineConstant] public const string TaxActiveOn = "TaxActiveOn";
            [InlineConstant] public const string TaxInactiveOn = "TaxInactiveOn";
            [InlineConstant] public const string TaxIsActive = "TaxIsActive";
            [InlineConstant] public const string TaxDbId = "TaxDbId";
            [InlineConstant] public const string TaxCreatedBy = "TaxCreatedBy";
            [InlineConstant] public const string TaxCreatedOn = "TaxCreatedOn";
            [InlineConstant] public const string TaxCreatedPc = "TaxCreatedPc";
            [InlineConstant] public const string TaxUpdatedBy = "TaxUpdatedBy";
            [InlineConstant] public const string TaxUpdatedOn = "TaxUpdatedOn";
            [InlineConstant] public const string TaxUpdatedPc = "TaxUpdatedPc";
            [InlineConstant] public const string TaxDeletedBy = "TaxDeletedBy";
            [InlineConstant] public const string TaxDeletedOn = "TaxDeletedOn";
            [InlineConstant] public const string TaxDeletedPc = "TaxDeletedPc";
            [InlineConstant] public const string TaxIsDelete = "TaxIsDelete";
        }
    }
}